### ISSUE TITLE
使用后获取不到数据？

### ISSUE THREAD

**Issue by itshu** [aruis/cordova-plugin-baidumaplocation#1]
"latitude": 5e-324,
    "lontitude": 5e-324,
但是我用6.2.3版本的时候是可以获取定位的，应该不是我key的问题。不明白什么原因

**Comment by orthuslee** [comment]
locType:167的话是因为在android6+上需要处理动态权限，把targetsdk改为22或者在增加对动态权限的处理即可。

**Comment by orthuslee** [comment]
试了下，在5.1下出现和你一样的问题505,\n
            \"locTypeDescription\": \"NetWork location failed because baidu location service check the key is unlegal,
            please check the key in AndroidManifest.xml !\",\n \"latitude\": 5e-324,\n \"lontitude\": 5e-324,\n
            \"radius\": 0,\n \"userIndoorState\": -1,\n \"direction\": -1\n}

**Comment by itshu** [comment]
跟android版本有关？低版本的不适配吗？

**Comment by itshu** [comment]
有没有解决办法？

**Comment by orthuslee** [comment]
发现是SHA1的问题，我用了这个检查到的SHA1和keystool获取的不一样，在百度的api控制台，修改SHA1后OK。你试试看是不是这个问题导致
![191344gbo4snpsn48r4bnb](https://cloud.githubusercontent.com/assets/22050030/24193589/be1a57d2-0f2d-11e7-8680-b7ff6712b2b5.png)

**Comment by orthuslee** [comment]
另外在sdk大于等于23以上的时候，是有问题的，只能降低版本，一直出现 locType:167，动态权限导致问题，需要在插件中处理申请动态权限

**Comment by itshu** [comment]
申请动态权限，我就不知道怎么弄了，我先看看上面那个，多谢

**Comment by KevinWang15** [comment]
@itshu @orthuslee 我实现了 Android 6.0+ 动态权限的支持，已发PR，可以先用我的试试看
https://github.com/KevinWang15/cordova-plugin-baidumaplocation

```
cordova plugin rm cordova-plugin-baidumaplocation
cordova plugin add https://github.com/KevinWang15/cordova-plugin-baidumaplocation --variable ANDROID_KEY="..." --variable IOS_KEY="..."
```
