### ISSUE TITLE
添加插件报错是什么原因呢？

### ISSUE THREAD

**Issue by dhunter221** [aruis/cordova-plugin-baidumaplocation#10]
安装插件后，进行模拟器编译：
xcode报错（xcode下真机测试一样是这个报错）：
Apple Mach-O Linker Error
Linker command failed with exit code 1(use -v to see invocation)

Android Studio报错：
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

附上我的版本：
Xcode 版本 8.3.2
Android Studio for mac 版本 2.3.3
cordova版本7.0.1
ionic版本3.4.0

**Comment by dhunter221** [comment]
已经解决了，给后来遇到同一个问题的说一下吧

xcode只需要在build setting里library search paths里添加一个到cordova-plugin-baidumaplocation的指向即可
例如添加"$(SRCROOT)/myapp/Plugins/cordova-plugin-baidumaplocation"即可消除xcode的报错

安卓的话，是因为模拟器的问题，用真机测试就什么问题都没有了。

**Comment by aruis** [comment]
感谢：）
