### ISSUE TITLE
如何设置参数？

### ISSUE THREAD

**Issue by xyxabcdiy** [aruis/cordova-plugin-baidumaplocation#11]
getCurrentPosition 函数中的 options 参数如何使用？

**Comment by CuiShiKang** [comment]
同问getCurrentPosition 函数中的 options 参数 如何使用

**Comment by xyxabcdiy** [comment]
@CuiShiKang 我看了下源代码，似乎还不支持自定义参数，所有参数都是预设好的，目前想要设置参数的话只能手动修改java文件了
