### ISSUE TITLE
ionic2如何使用？

### ISSUE THREAD

**Issue by mylhyl** [aruis/cordova-plugin-baidumaplocation#14]

**Comment by aruis** [comment]
这本身是cordova插件，和ionic、angularjs1x没有必然联系。 所以你大可像使用其他cordova插件那样使用本插件。

**Comment by mylhyl** [comment]
exec(win, fail, 'BaiduMapLocation', 'getCurrentPosition', options);
改为
exec(win, fail, 'BaiduMapLocation', 'getCurrentPosition', [options]);
成功

**Comment by mylhyl** [comment]
cordova.js会将options当成一个数组使用，一直异常报异常“JSON ERROR”

**Comment by aruis** [comment]
确实，我的代码有问题。 如果可以，欢迎你提交一个PullRequest
