### ISSUE TITLE
如何实现实时获取位置信息，

### ISSUE THREAD

**Issue by moonlitnighta** [aruis/cordova-plugin-baidumaplocation#16]
，如何实现实时获取位置信息呢，目前指看到只有getCurrentPosition方法，@ aruis大师给个思路啊

**Comment by aruis** [comment]
抱歉，你是要持续追踪位置吧，那我确实没啥好想法。实在不行，你就多次调用getCurrentPosition 呢？

**Comment by liugogal** [comment]
实测，有一个小问题  ，第一次的调用的时候，只能获取经纬度，第二次调用才能获取详细地址。另外数据包里面没有“省”属性。

**Comment by liugogal** [comment]
刚刚看了一下代码 问题应该出现在这里：
if(!flag)        
        {
            CDVPluginResult* result = [CDVPluginResult resultWithStatus:CDVCommandStatus_OK messageAsDictionary:_data];
            [result setKeepCallbackAsBool:TRUE];
            [_locService stopUserLocationService];
            [self.commandDelegate sendPluginResult:result callbackId:_execCommand.callbackId];
            _execCommand = nil;
        }
当你调用了反查函数之后，会很快返回了flag,这里并不会立马将反查结果写入_data, 反查结果是onGetReverseGeoCodeResult里面执行，这里是异步的。而在这个地方，直接就将反查之前的_data就返回给了js，所以第一次我获取到的未包含省市区相关信息。第二次调用的时候，由于已经有了缓存，第一次的反查数据已经写入了_data，所以返回的结果是包含了省市区的，其实这个时候得到的值是上次调用反查接口返回的值。

这里我建议  在if(!flag) {}  中 不做返回数据的处理。让_execCommand 在onGetReverseGeoCodeResult中去回调即可。

**Comment by aruis** [comment]
不知兄弟是否愿意提交一个PR，修正这个问题呢？ @liugogal  万分感谢；）

**Comment by liugogal** [comment]
我也没做什么处理，就只是注释了if(!flag) {}  里面的代码就行，当然你可以在里面做一些其他的处理或者通知，不过别在这里send就行。  最终发送给js的地方 其实是 onGetReverseGeoCodeResult这个回调里面，不用做其他额外处理。

**Comment by aruis** [comment]
已经按你说的改了，烦请帮忙复查一下；） @liugogal

**Comment by liugogal** [comment]
ok，应该问题不大，一会儿测试了 给你反馈。
