### ISSUE TITLE
ios 返回数据缺少 province

### ISSUE THREAD

**Issue by liugogal** [aruis/cordova-plugin-baidumaplocation#17]
[_data setValue:countryCode forKey:@"countryCode"];
        [_data setValue:country forKey:@"country"];
        //[_data setValue:adCode forKey:@"citycode"];
        [_data setValue:city forKey:@"city"];
        [_data setValue:district forKey:@"district"];
        [_data setValue:streetName forKey:@"street"];
        [_data setValue:addr forKey:@"addr"];
        [_data setValue:sematicDescription forKey:@"locationDescribe"];

**Comment by liugogal** [comment]
android 端也是 ，估计是兄弟忘记加了吧

**Comment by liugogal** [comment]
ios:
NSString* province = component.province;

[_data setValue:province forKey:@"province"];

android:
json.put("city", location.getProvince());

**Comment by aruis** [comment]
感谢你的建议，我已经追加province 字段了。
