### ISSUE TITLE
iOS中编译出错，提示-lcrypto这个库找不到

### ISSUE THREAD

**Issue by zhuzhiqiang** [aruis/cordova-plugin-baidumaplocation#18]

**Comment by zhuzhiqiang** [comment]
我改了plugin.xml,修改如下：

        <framework src="libs/ios/BaiduMapAPI_Base.framework" custom="true"/>
        <framework src="libs/ios/BaiduMapAPI_Location.framework" custom="true"/>
        <source-file src="libs/ios/thirdlibs/libcrypto.a" framework="true"/>
        <source-file src="libs/ios/thirdlibs/libssl.a" framework="true"/>

**Comment by zhuzhiqiang** [comment]
这样就不会编译出错了

**Comment by aruis** [comment]
能否看下 你用的本插件的哪个版本？

**Comment by zhuzhiqiang** [comment]
我的是之前的版本，搞错了，哈哈
