### ISSUE TITLE
ios无法定位，没有开启权限

### ISSUE THREAD

**Issue by jinzis** [aruis/cordova-plugin-baidumaplocation#24]
ios没有弹出开启权限的弹窗，导致定位失败！

**Comment by aruis** [comment]
理论上。 第一次使用定位功能的时候，app 会弹框提示的。 你那没有这个提示么？  你看下xcode 项目配置info 选项卡 Privacy - Location When In Use Usage Description 这个，你输入相关信息么？

**Comment by jinzis** [comment]
可以了，是我弄错了，非常感谢！
