### ISSUE TITLE
为什么第一次使用能正常定位返回数据  第二次就报错

### ISSUE THREAD

**Issue by luojianguang** [aruis/cordova-plugin-baidumaplocation#29]
请问   为什么第一次使用能正常定位并返回数据  第二次就报如此错   
{"locType": 505, "locTypeDescription": "NetWork location failed because baidu location service check the key is unlegal, please check the key in AndroidManifest.xml !", "latitude": 5e-324, "longitude": 5e-324, "radius": 0, "userIndoorState": -1, "direction": -1 }

**Comment by aruis** [comment]
你是不是  key 填错了。 如果key 填错了。  baidu 也会偶尔放行的。

**Comment by luojianguang** [comment]
感谢   已经解决了
