### ISSUE TITLE
请问一下，这个不支持 ionic3吗？

### ISSUE THREAD

**Issue by wangliyang206** [aruis/cordova-plugin-baidumaplocation#34]
安装时会报找不到AndroidManifest.xml 文件！！！
npm install --save @ionic-native/<请问此处添什么？添baidumaplocation会报错哟！>
求解~

**Comment by SSRChen** [comment]
我也遇到这个问题，我的操作是
先cordova platform rm android
然后安装插件
打开文件  plugins/cordova-plugin-baidumaplocation/config.xml    87-93行改成

```
<source-file src="src/android/BaiduMapLocation.java" target-dir="app/src/com/aruistar/cordova/baidumap"/>
        <source-file src="libs/android/armeabi/liblocSDK7a.so" target-dir="app/libs/armeabi"/>
        <source-file src="libs/android/armeabi-v7a/liblocSDK7a.so" target-dir="app/libs/armeabi-v7a"/>
        <source-file src="libs/android/arm64-v8a/liblocSDK7a.so" target-dir="app/libs/arm64-v8a"/>
        <source-file src="libs/android/x86/liblocSDK7a.so" target-dir="app/libs/x86"/>
        <source-file src="libs/android/x86_64/liblocSDK7a.so" target-dir="app/libs/x86_64"/>
        <source-file src="libs/android/BaiduLBS_Android.jar" target-dir="app/libs"/>

```
再  cordova platform add android


好了 试看看

**Comment by SSRChen** [comment]
ionic-native 是 ionic 对 cordova插件进行进一步封装
你也可以直接使用插件
`
declare const baidumap_location: any;

@Injectable()
export class GeolocationService {
    ……
    ……
getGeopositionData() {
    if (typeof baidumap_location === "undefined")    return;
   baidumap_location.getCurrentPosition(result => {
            ……
        }, error => {
            ……
        });
}
}`

注意要在 platform.ready() 后再来调用原生插件， 否则 baidumap_location可能会是undefined

**Comment by aruis** [comment]
追加ionic3项目的demo https://github.com/aruis/testbmap-cordova-ionic3 
感谢 @SSRChen 提供方案
