### ISSUE TITLE
请问有angular4+ionic3引用的demo吗？

### ISSUE THREAD

**Issue by qiushisnail** [aruis/cordova-plugin-baidumaplocation#36]

**Comment by aruis** [comment]
一周之内吧，尽量把现有问题升级一下，然后出个基于新版ionic的demo

**Comment by yaoxiaofdou** [comment]
ionic 3引入后有点不稳定啊，经常被客户反馈定位一直出不来～～～～没办法就让他们重启app，一般重启几次就又可以定位了～～～～这～～～

**Comment by yaoxiaofdou** [comment]
这个有什么好的解决方法吗 ？

**Comment by aruis** [comment]
我这个就在ionic1 版本的生产环境下用过。  那也是一年多了。  现在已经没有精力跟进了。  只能说有空研究下，时间和质量都不敢保证。 真是对不起啊。 @yaoxiaofdou

**Comment by aruis** [comment]
追加ionic3项目的demo https://github.com/aruis/testbmap-cordova-ionic3 @qiushisnail
