### ISSUE TITLE
插件add失败

### ISSUE THREAD

**Issue by ray-zyh** [aruis/cordova-plugin-baidumaplocation#4]
添加插件的时候很慢.但是最后显示
Fetching plugin "cordova-plugin-baidumaplocation" via npm
Error: Failed to fetch plugin cordova-plugin-baidumaplocation via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: shasum check failed for C:\Users\dell\AppData\Local\Temp\npm-6104-c3fd1d90\registry.npmjs.org\cordova-plugin-baidumaplocation\-\cordova-plugin-baidumaplocation-2.0.2.tgz
Expected: d1f8a8c01e0a018cfd3e216aeed8e74dff31cd75
Actual:   08fa3e2f08192d081a7457d33c1f1d23890e4313
From:     http://registry.npmjs.org/cordova-plugin-baidumaplocation/-/cordova-plugin-baidumaplocation-2.0.2.tgz
我申请了安卓key 浏览器key ios key,都 试了还是下载失败.是不是cordove不再支持此插件了

**Comment by aruis** [comment]
国内访问npmjs 确实慢。建议你尝试替换成淘宝的地址。 简单使用可以试试这个  npm config set registry https://registry.npm.taobao.org   ， 更推荐的是 nrm 插件，一劳永逸：npm install -g nrm

**Comment by aruis** [comment]
刚有上传了新版本，确定还是可以更新到的，就是包有点大，估计会慢些，这个确实没别的好办法了。
