### ISSUE TITLE
baidumap_location.getCurrentPosition 无作用

### ISSUE THREAD

**Issue by qiushisnail** [aruis/cordova-plugin-baidumaplocation#40]
baidumap_location.getCurrentPosition
对象能获取 但是回调方法不起作用  申请了自己的百度密钥了

**Comment by qiushisnail** [comment]
之前使用3.2.0 版本没有报错，现在使用最新版本就出问题 我是用在ionic3上

**Comment by aruis** [comment]
能贴出具体使用代码么，我可以跟进测试一下。

**Comment by liuman2** [comment]
我也是回调不起作用

**Comment by kirin-yuen** [comment]
Hi, 参考 #64 的解决方法
