### ISSUE TITLE
Cordova version: 6.5.0插件失效，无法获取地址。一直报超时：Position retrieval timed out.

### ISSUE THREAD

**Issue by ITKing80** [aruis/cordova-plugin-baidumaplocation#43]
之前我cordova version:5.4.0的时候是正常的
现在：
Cordova version: 6.5.0
"android-26"
Name: Android 8.0.0
Type: Platform
API level: 26
Revision: 2

无法获取地址，一直报超时。Position retrieval timed out.

安装插件日志：
Fetching plugin "cordova-plugin-baidumaplocation@4.0.1" via npm
Installing "cordova-plugin-baidumaplocation" for android
ANDROID_HOME=D:\Program Files (x86)\Android\android-sdk
JAVA_HOME=D:\Program Files\Java\jdk1.8.0_131
Subproject Path: CordovaLib
Configuration 'compile' in project ':' is deprecated. Use 'implementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_3ipw43oaqfc43xtgb0czhnjef.run(D:\workspace\aaa\platforms\android\build.gradle:143)
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
:clean
:CordovaLib:clean

BUILD SUCCESSFUL in 5s
2 actionable tasks: 2 executed
cordova : Picked up _JAVA_OPTIONS: -Xmx512M
所在位置 行:1 字符: 1
+ cordova plugin add cordova-plugin-baidumaplocation --variable ANDROID ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Picked up _JAVA_OPTIONS: -Xmx512M:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Saved plugin info for "cordova-plugin-baidumaplocation" to config.xml

APP运行日志：
W/System.err( 9289): **java.lang.ClassNotFoundException: com.aruistar.cordova.baidumap.BaiduMapLocation**
W/System.err( 9289): 	at java.lang.Class.classForName(Native Method)
W/System.err( 9289): 	at java.lang.Class.forName(Class.java:324)
W/System.err( 9289): 	at java.lang.Class.forName(Class.java:285)
W/System.err( 9289): 	at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:489)
W/System.err( 9289): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
W/System.err( 9289): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
W/System.err( 9289): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
W/System.err( 9289): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err( 9289): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 9289): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
W/System.err( 9289): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 9289): 	at android.os.Looper.loop(Looper.java:150)
W/System.err( 9289): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/System.err( 9289): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.aruistar.cordova.baidumap.BaiduMapLocation" on path: DexPathList[[zip file "/data/app/com.xxx.yyy-1/base.apk"],nativeLibraryDirectories=[/data/app/com.xxx.yyy-1/lib/arm64, /vendor/lib64, /system/lib64]]
W/System.err( 9289): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
W/System.err( 9289): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
W/System.err( 9289): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
W/System.err( 9289): 	... 13 more
W/System.err( 9289): 	Suppressed: java.lang.ClassNotFoundException: com.aruistar.cordova.baidumap.BaiduMapLocation
W/System.err( 9289): 		at java.lang.Class.classForName(Native Method)
W/System.err( 9289): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
W/System.err( 9289): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
W/System.err( 9289): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
W/System.err( 9289): 		... 14 more
W/System.err( 9289): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
I/System.out( 9289): Error adding plugin com.aruistar.cordova.baidumap.BaiduMapLocation.
W/System.err( 9289): java.lang.NullPointerException: Attempt to invoke virtual method 'void org.apache.cordova.CordovaPlugin.privateInitialize(java.lang.String, org.apache.cordova.CordovaInterface, org.apache.cordova.CordovaWebView, org.apache.cordova.CordovaPreferences)' on a null object reference
W/System.err( 9289): 	at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:171)
W/System.err( 9289): 	at org.apache.cordova.PluginManager.exec(PluginManager.java:122)
W/System.err( 9289): 	at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
W/System.err( 9289): 	at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
W/System.err( 9289): 	at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 9289): 	at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
W/System.err( 9289): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 9289): 	at android.os.Looper.loop(Looper.java:150)
W/System.err( 9289): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by aruis** [comment]
这么尴尬，相当于这个插件的java文件，要么是没参与编译，要么是没找到。

**Comment by ITKing80** [comment]
是的，不知道是否测试过cordova6.5.0 android26?

**Comment by aruis** [comment]
我连我自己在哪个版本跑的都记不住了， 应该就是前端时间心血来潮，把ionic和cordova都升到最新版，然后跑了一发，觉得没问题，就没测别的。https://github.com/aruis/testbmap-cordova-ionic3

**Comment by ITKing80** [comment]
我还是ionic1.7

**Comment by aruis** [comment]
这，我现在电脑没有ionic1 的环境了。你知道怎么装么？ 自从ionic大跃进后，我已经hold不住了。

**Comment by ITKing80** [comment]
npm install -g cordova ionic@1

**Comment by aruis** [comment]
好滴，多谢，我试试哈。

**Comment by ITKing80** [comment]
感谢！

**Comment by aruis** [comment]
![2018-06-29 16 54 12](https://user-images.githubusercontent.com/1785495/42083303-11c82f7e-7bbd-11e8-8e6b-92befe4a5bd1.png)
cordova 是 8 ，是不是不太好？

**Comment by ITKing80** [comment]
你先试试吧，应该关键是这个：cordova platform add android@6

**Comment by aruis** [comment]
ok

**Comment by ITKing80** [comment]
或者npm install -g cordova@6

**Comment by ITKing80** [comment]
{
    "android": "6.4.0"
}

**Comment by aruis** [comment]
找到原因了。 在ionic1x 里面添加 android ，android 的src 实际路径是 android/src 。 但是我这个版本在ionic3实验的时候， src路径是 android/app/src  ， 还有libs也有同样的问题。
临时解决方案，你可以在android 文件夹下，手动把app/下的文件复制到  android/libs 和/android/src下，如图，
<img width="616" alt="image" src="https://user-images.githubusercontent.com/1785495/42089823-7c16ed52-7bd1-11e8-9728-ac63c7ad71fb.png">
亲测已经成功

**Comment by ITKing80** [comment]
感谢，我明天试一下
