### ISSUE TITLE
ionic3上使用插件并打了android包，测试时一直报超时

### ISSUE THREAD

**Issue by arhaha** [aruis/cordova-plugin-baidumaplocation#47]
环境：
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node  : v8.11.1
    npm   : 5.6.0
    OS    : macOS High Sierra
    Xcode : Xcode 9.3 Build version 9E145

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

代码:
getPosition(timeout: number = 5 * 1000): Promise < any > {
  return new Promise<any>((resolve, reject) => {
    baidumap_location.getCurrentPosition((result) => {
      console.log("baidumap_location result:", result);
      resolve(result);
    }, (error) => {
      console.error("baidumap_location error:", error);
      reject(error);
    }, { timeout: timeout });
  });
}

描述：
执行getPosition只会返回error，error信息为「code: -1,message: "Position retrieval timed out."」

**Comment by aruis** [comment]
再检查下安卓手机有没有给app 定位的权限呢？

**Comment by arhaha** [comment]
有给的，我后来把版本降到3.0.2是可以用的，但是4.0就是如果不设置超时的话就会永远的不返回，而设置了超时的话最后就会报超时。

**Comment by aruis** [comment]
明白了，参考这个最后几句[https://github.com/aruis/cordova-plugin-baidumaplocation/issues/43](https://github.com/aruis/cordova-plugin-baidumaplocation/issues/43)

**Comment by arhaha** [comment]
非常感谢，参考你的解决，我把plugin.xml下关于库的导入修改成如下

`        <source-file src="src/android/BaiduMapLocation.java" target-dir="src/com/aruistar/cordova/baidumap"/>
        <source-file src="libs/android/armeabi/libindoor.so" target-dir="libs/armeabi"/>
        <source-file src="libs/android/armeabi/liblocSDK7b.so" target-dir="libs/armeabi"/>
        <source-file src="libs/android/armeabi-v7a/libindoor.so" target-dir="libs/armeabi-v7a"/>
        <source-file src="libs/android/armeabi-v7a/liblocSDK7b.so" target-dir="libs/armeabi-v7a"/>
        <source-file src="libs/android/arm64-v8a/libindoor.so" target-dir="libs/arm64-v8a"/>
        <source-file src="libs/android/arm64-v8a/liblocSDK7b.so" target-dir="libs/arm64-v8a"/>
        <source-file src="libs/android/x86/libindoor.so" target-dir="libs/x86"/>
        <source-file src="libs/android/x86/liblocSDK7b.so" target-dir="libs/x86"/>
        <source-file src="libs/android/x86_64/libindoor.so" target-dir="libs/x86_64"/>
        <source-file src="libs/android/x86_64/liblocSDK7b.so" target-dir="libs/x86_64"/>
        <source-file src="libs/android/BaiduLBS_Android.jar" target-dir="libs"/>`

经过测试使用正常。
