### ISSUE TITLE
请问下这个可以禁止虚拟定位吗？

### ISSUE THREAD

**Issue by plat10510** [aruis/cordova-plugin-baidumaplocation#54]
百度地图里好像有个接口setEnableSimulateGps(boolean enableSimulateGps)可以防止虚拟定位，这个项目有或者可以加吗？

**Comment by aruis** [comment]
欢迎你通过Pull Request来丰富这个项目的功能

**Comment by plat10510** [comment]
大神，我试着将你的这个项目用glup封装了一下，弄成可以在ionic里使用并且更符合ionic风格的插件了，完美运行，感谢~，我把它放在我github了
