### ISSUE TITLE
cordova plugin add 安装插件失败

### ISSUE THREAD

**Issue by Sight4** [aruis/cordova-plugin-baidumaplocation#56]
你好，在安装插件时显示 UnhandledPromiseRejectionWarning: CordovaError: Variable(s) missing (use: --variable IOS_KEY=value)，由于暂时只使用安卓，所以只使用了 --variable ANDROID_KEY=“<ANDROID_KEY>”，看到项目首页说明可以只提供一个参数，现在是否必须提供两个？

**Comment by Sight4** [comment]
补充一下
cordova plugin add cordova-plugin-baidumaplocation --variable ANDROID_KEY="<ANDROID_KEY>"  --variable IOS_KEY="" 会报同样的错误

**Comment by aruis** [comment]
嗯，之前设计缺陷，你尝试填入两个非空值试试看；）

**Comment by Sight4** [comment]
好的，按照你的操作指引，已经OK了，谢谢，只是感觉这样有点怪怪的
