### ISSUE TITLE
cordova不能定位！

### ISSUE THREAD

**Issue by zhzsh3985** [aruis/cordova-plugin-baidumaplocation#6]
没有安装ionic,直接在cordova中安装此plugin,html5中提示baidumap_location没有定义。直接发布成apk，在手机上没有反应！会是什么问题呢？
  baidumap_location.getCurrentPosition(function (result) {
            alert("================")
            alert(JSON.stringify(result, null, 4));
        }, function (error) {
        });

**Comment by zhzsh3985** [comment]
地图的key跟定位的key难道不是一个么？

**Comment by DragonEmperorG** [comment]
这个插件只封装了定位功能，还是将整个Andriod和IOS的SDK都封装了？能否用于显示百度地图啊？

**Comment by aruis** [comment]
key 可以是一个key ，只要申请的时候都勾选就OK了。 @zhzsh3985

**Comment by aruis** [comment]
指封装了 定位功能。 @DragonEmperorG

**Comment by aruis** [comment]
刚又测试了最新版本，还是可以用的。 请再试试；） @zhzsh3985
