### ISSUE TITLE
您好，在plugin.xml中看到您写的target-dir路径应该是容易出问题的

### ISSUE THREAD

**Issue by plat10510** [aruis/cordova-plugin-baidumaplocation#61]
target-dir应该从src开始写，如果按现在这样到了android studio里BaiduMapLocation.java就会说package不对。之后我是这么改的
`<source-file src="src/android/BaiduMapLocation.java" target-dir="src/com/aruistar/cordova/baidumap"/>`

**Comment by aruis** [comment]
这可能跟不同 Cordova版本 生成的 android 项目构造有关。

**Comment by plat10510** [comment]
是的，这很烦人
