### ISSUE TITLE
在Ionic3中baidumap_location.getCurrentPosition 方法没作用根本就不进入回调函数

### ISSUE THREAD

**Issue by wenzirang** [aruis/cordova-plugin-baidumaplocation#63]
在调试的过程中发现其实是由getCurrentPosition方法的 但是就是不会进入回调函数，还望作者跟进一下

**Comment by qingzhou5989** [comment]
百度ak正确并且有签名的前提下，只要把  platforms\android\app下面的两个文件夹（libs，src）拷到   platforms\android 文件夹下面再build一次就可以正常使用定位了
