### ISSUE TITLE
定位刚进程序能定位，第二次请求就报错了，报key错误，

### ISSUE THREAD

**Issue by livewithme** [aruis/cordova-plugin-baidumaplocation#7]
05-16 10:30:37.512 13192-13192/com.chumi.qscrm I/chromium: [INFO:CONSOLE(38)] "坐标=============获取成功{"time":"2017-05-16 10:30:38","locType":161,"locTypeDescription":"NetWork location successful!","latitude":29.532723,"lontitude":106.575376,"radius":40,"countryCode":"0","country":"中国","citycode":"132","city":"重庆市","district":"南岸区","street":"江南大道","addr":"中国重庆市南岸区江南大道8号","userIndoorState":1,"direction":-1,"locationDescribe":"在万达国际写字楼2栋附近"}", source: file:///android_asset/www/js/checkWork.js (38)
05-16 10:30:37.622 13192-13192/com.chumi.qscrm I/chromium: [INFO:CONSOLE(42)] "坐标=============获取显示106.575376==================29.532723", source: file:///android_asset/www/js/checkWork.js (42)
05-16 10:30:43.732 13192-13192/com.chumi.qscrm I/chromium: [INFO:CONSOLE(7)] "初始化======checkwork", source: file:///android_asset/www/js/checkWork.js (7)
05-16 10:30:44.032 13192-13192/com.chumi.qscrm I/chromium: [INFO:CONSOLE(38)] "坐标=============获取成功{"locType":505,"locTypeDescription":"NetWork location failed because baidu location service check the key is unlegal, please check the key in AndroidManifest.xml !","latitude":5e-324,"lontitude":5e-324,"radius":0,"userIndoorState":-1,"direction":-1}", source: file:///android_asset/www/js/checkWork.js (38)

**Comment by livewithme** [comment]
解决了，开发版，和发布版，有些区别

**Comment by BLSM53** [comment]
@livewithme 请问您指的区别是什么？具体是怎么解决的呢？

**Comment by YDJSZY** [comment]
一样的错。。。没人具体说下什么原因？

**Comment by livewithme** [comment]
我记得遇到这种问题是因为，你运行的包，与打包的签名有些不一致，需要在gradle 中配置固定的签名， ------------------ 原始邮件 ------------------
发件人: "YDJSZY"<notifications@github.com>
发送时间: 2019年10月28日(星期一) 中午11:08
收件人: "aruis/cordova-plugin-baidumaplocation"<cordova-plugin-baidumaplocation@noreply.github.com>;
抄送: "luyaoyao"<382708580@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [aruis/cordova-plugin-baidumaplocation] 定位刚进程序能定位，第二次请求就报错了，报key错误， (#7)



一样的错。。。没人具体说下什么原因？
 
&mdash;
