### ISSUE TITLE
ios 12.2-13.2 获取不到addr字段，坐标也有偏移

### ISSUE THREAD

**Issue by C-racker** [aruis/cordova-plugin-baidumaplocation#82]
其他版本未测，android没问题

**Comment by C-racker** [comment]
修改.mm文件解决了

**Comment by chary2060** [comment]
请问，怎么修改的啊？

**Comment by chary2060** [comment]
> 修改.mm文件解决了

请问，怎么修改的啊？

**Comment by C-racker** [comment]
> > 修改.mm文件解决了
> 
> 请问，怎么修改的啊？

仅供参考 https://github.com/C-racker/cordova-plugin-baidumaplocation
